worker_processes  1;
events {
    worker_connections 1024;
}

http {
    ## enable compression for JSON
    gzip on;
    gzip_types application/json;
    gzip_min_length 1000;

    upstream fastapi { server app:8000; }

    server {
        listen 80;
        server_name _;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_buffering off;

         # ---------- WebSocket ----------
        location /ws/ {
            proxy_pass              http://fastapi;
            proxy_set_header        Upgrade           $http_upgrade;
            proxy_set_header        Connection        $connection_upgrade;
            proxy_read_timeout      86400;
            proxy_set_header        Sec-WebSocket-Protocol $http_sec_websocket_protocol;
        }

        location / {
            proxy_pass http://fastapi;
        }
    }
}
